sudo: true
dist: trusty

language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libssl-dev
      - libevent-dev
      - libboost-all-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls


rust:
  - nightly

install:
  - git clone https://github.com/bitcoin/bitcoin
  - cd bitcoin
  - ./autogen.sh && .configure && make && sudo make install
  - sudo ldconfig /usr/local/lib

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench 

after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  #- travis-cargo coveralls --no-sudo --verify
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/bitcrust_lib-*; fi

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    # encrypted github token for doc upload (see `GH_TOKEN` link above)
    # - secure: "..."

