[package]
name = "bitcrust"
version = "0.1.0"
authors = ["Tomas van der Wansem <tomas@tomasvdw.nl>"]


[lib]
name = "bitcrust_lib"
path = "bitcrust-lib/src/lib.rs"

[dependencies]
lmdb-rs = "0.7"
serde = "0.8.8"
serde_json = "0.8.2"
serde_macros = "0.8.2"
byteorder = "0.5"
rustc-serialize = "0.3"
itertools = "0.5.1"
memmap = "0.4.0"

[[bin]]
name = "bitcrust_admin"
path = "bitcrust-admin/src/main.rs"

