[package]
name = "bitcrust"
version = "0.1.0"
authors = ["Tomas van der Wansem <tomas@tomasvdw.nl>"]


[lib]
name = "bitcrust_lib"
path = "bitcrust-lib/src/lib.rs"

[dependencies]
rustc-serialize = "0.3"
byteorder = "0.4"
lmdb-rs = "0.5"
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"

[[bin]]
name = "bitcrust_admin"
path = "bitcrust-admin/src/main.rs"

