[package]
name = "bitcrust-net"
version = "0.1.0"
authors = ["Tomas van der Wansem <tomas@tomasvdw.nl>"]

[dependencies]
circular = "~0.2"
byteorder = "1"
log = "0.3"
multiqueue = "~0.3.2"
nom = "^2.2"
rusqlite = "~0.11"
sha2 = "0.5"

[dev-dependencies]
env_logger = "0.4.2"