[package]
name = "bitcrust-net"
version = "0.1.0"
authors = ["Tomas van der Wansem <tomas@tomasvdw.nl>"]

[dependencies]
byteorder = "1"
log = "0.3"
nom = "^2.2"
sha2 = "0.5"

[dev-dependencies]
env_logger = "0.4.2"